// Central factory of React Query keys — one source of truth so invalidation is consistent.
export const qk = {
  borrowers: ['borrowers'] as const,
  borrowersByStatus: (status: string) => ['borrowers', { status }] as const,
  borrower: (id: string) => ['borrowers', id] as const,
  loans: ['loans'] as const,
  loan: (id: string) => ['loans', id] as const,
  loanShare: (id: string) => ['loans', id, 'share'] as const,
  dashboard: ['dashboard'] as const,
  reportSummary: (months: number) => ['reports', 'summary', months] as const,
  subscription: ['subscription'] as const,
  me: ['me'] as const,
  billingSettings: ['settings', 'billing'] as const,
  chargeHistory: (status?: string) => ['settings', 'billing', 'history', status ?? 'all'] as const,
  chargeHistorySummary: ['settings', 'billing', 'history', 'summary'] as const,
  whatsappStatus: ['whatsapp', 'status'] as const,
  adminUsers: ['admin', 'users'] as const,
  adminUsersByStatus: (status: string) => ['admin', 'users', { status }] as const,
  adminCoupons: ['admin', 'coupons'] as const,
};
